In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
sns.set(color_codes=True)

In [2]:
df = pd.read_csv("dataset/merged_data_scaled.csv")
df.head()

,State,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,Incidence_Rate,Avg_Ann_Incidence,recent_trend,Mortality_Rate,Avg_Ann_Deaths
0,AK,5.766244,5.368211,684.085786,3.451072,1.899342,17.285424,139.776732,402.796797,114.666736,5.599848,6.292671,566,540,19.803971,1.033895,stable,16.123403,2.257616
1,AK,5.567629,5.399430,684.938033,3.465468,1.900102,20.277411,133.923171,456.077918,132.432609,6.278214,5.878096,1707,564,19.803971,1.033895,stable,16.123403,2.257616
2,AK,9.163722,9.424631,686.074037,3.462218,1.899831,18.557351,139.006510,406.099435,116.720717,8.488215,8.368044,122426,21393,95.073464,3.759435,stable,51.604112,2.951143
3,AK,7.617149,7.637853,694.582263,3.441905,1.899982,19.594522,126.304609,528.643550,170.332753,6.865869,6.835111,6627,1774,97.210195,1.623884,stable,64.329065,1.368471
4,AK,3.480220,3.574287,697.413750,3.463020,1.899853,17.179963,147.476683,395.731047,89.962742,5.091711,4.407670,349,67,19.803971,1.033895,stable,16.123403,2.257616

In [3]:
df_copy = df.copy()
df_copy.head()

,State,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,Incidence_Rate,Avg_Ann_Incidence,recent_trend,Mortality_Rate,Avg_Ann_Deaths
0,AK,5.766244,5.368211,684.085786,3.451072,1.899342,17.285424,139.776732,402.796797,114.666736,5.599848,6.292671,566,540,19.803971,1.033895,stable,16.123403,2.257616
1,AK,5.567629,5.399430,684.938033,3.465468,1.900102,20.277411,133.923171,456.077918,132.432609,6.278214,5.878096,1707,564,19.803971,1.033895,stable,16.123403,2.257616
2,AK,9.163722,9.424631,686.074037,3.462218,1.899831,18.557351,139.006510,406.099435,116.720717,8.488215,8.368044,122426,21393,95.073464,3.759435,stable,51.604112,2.951143
3,AK,7.617149,7.637853,694.582263,3.441905,1.899982,19.594522,126.304609,528.643550,170.332753,6.865869,6.835111,6627,1774,97.210195,1.623884,stable,64.329065,1.368471
4,AK,3.480220,3.574287,697.413750,3.463020,1.899853,17.179963,147.476683,395.731047,89.962742,5.091711,4.407670,349,67,19.803971,1.033895,stable,16.123403,2.257616

In [4]:
df_copy.drop(['State', 'recent_trend'] ,axis=1, inplace=True)
df_copy.head()

,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,Incidence_Rate,Avg_Ann_Incidence,Mortality_Rate,Avg_Ann_Deaths
0,5.766244,5.368211,684.085786,3.451072,1.899342,17.285424,139.776732,402.796797,114.666736,5.599848,6.292671,566,540,19.803971,1.033895,16.123403,2.257616
1,5.567629,5.399430,684.938033,3.465468,1.900102,20.277411,133.923171,456.077918,132.432609,6.278214,5.878096,1707,564,19.803971,1.033895,16.123403,2.257616
2,9.163722,9.424631,686.074037,3.462218,1.899831,18.557351,139.006510,406.099435,116.720717,8.488215,8.368044,122426,21393,95.073464,3.759435,51.604112,2.951143
3,7.617149,7.637853,694.582263,3.441905,1.899982,19.594522,126.304609,528.643550,170.332753,6.865869,6.835111,6627,1774,97.210195,1.623884,64.329065,1.368471
4,3.480220,3.574287,697.413750,3.463020,1.899853,17.179963,147.476683,395.731047,89.962742,5.091711,4.407670,349,67,19.803971,1.033895,16.123403,2.257616

In [5]:
df_copy.describe()

,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,Incidence_Rate,Avg_Ann_Incidence,Mortality_Rate,Avg_Ann_Deaths
count,3134.000000,3134.000000,3134.000000,3134.000000,3134.000000,3134.000000,3134.000000,3134.000000,3134.000000,3134.000000,3134.000000,3.134000e+03,3134.000000,3134.000000,3134.000000,3134.000000,3134.000000
mean,7.476456,7.731500,6474.491840,3.435509,1.898005,17.255620,123.775032,396.922473,104.289519,7.193966,6.522421,4.487357e+04,5968.701021,98.427307,2.676764,54.089623,2.259279
std,1.496206,1.502265,2819.615083,0.012722,0.000792,0.948523,16.525184,64.279581,12.205534,0.854043,1.115512,1.406455e+05,24657.276997,43.260663,0.873315,20.100357,0.552969
min,1.605981,1.607574,381.317361,3.386007,1.893983,11.450467,43.967328,85.138235,39.146679,3.138798,1.350691,3.300000e+01,4.000000,16.163093,1.033895,8.663262,0.982487
25%,6.573242,6.829987,4460.963037,3.427665,1.897507,16.941756,123.353027,395.731047,99.087473,6.653407,5.858613,4.657500e+03,633.000000,76.160788,2.103681,43.361171,1.889504
50%,7.486758,7.728156,6381.825496,3.435584,1.898002,17.179963,123.353027,395.731047,103.617144,7.154055,6.513921,1.110800e+04,1529.000000,103.654355,2.703862,55.411212,2.257616
75%,8.359969,8.613885,9175.418981,3.443080,1.898474,17.374726,123.353027,395.731047,108.906802,7.713602,7.193351,2.976475e+04,3834.000000,125.247758,3.242220,66.187766,2.609197
max,13.376474,13.655803,11003.830349,3.481298,1.900845,22.032414,243.960837,780.552820,191.224413,10.081876,10.767165,4.230137e+06,837175.000000,374.827240,5.377341,143.725413,3.898289

In [6]:
numerical_features = ['M_Poverty', 'F_Poverty', 'FIPS','Med_Income', 'Med_Income_White',
                      'Med_Income_Black', 'Med_Income_Nat_Am', 'Med_Income_Asian', 
                      'Hispanic', 'M_With', 'M_Without', 'Incidence_Rate', 'Avg_Ann_Incidence',
                     'Mortality_Rate']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df_copy.iloc[:, :-1], df_copy.iloc[:, -1], test_size=0.2, 
                                                    random_state=42)

In [8]:
X_train.head()

,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,Incidence_Rate,Avg_Ann_Incidence,Mortality_Rate
755,6.998475,7.711762,4092.060529,3.437706,1.897960,17.179963,123.353027,395.731047,125.563736,7.099507,5.658722,13000,822,140.666552,2.914860,76.208457
3123,8.101085,8.425250,11000.552657,3.447285,1.898692,16.702670,126.701496,395.731047,105.826888,7.817045,7.431036,33595,5518,89.227759,3.143030,44.936909
221,10.254187,10.391529,1723.450159,3.452937,1.899102,18.618808,142.504053,420.910656,113.297728,8.674423,8.692306,186064,30108,61.417919,3.967805,31.031137
543,8.011917,8.267416,3663.221438,3.453751,1.898925,19.295743,159.671684,413.399623,120.453396,7.774143,6.985116,32223,2228,66.672337,3.006695,37.050272
1395,7.893845,8.020463,6349.130139,3.425797,1.897343,15.708804,69.948693,85.138235,71.249069,7.177111,6.206763,11811,1435,88.522280,2.336911,46.772909

# Linear Regression

The linear regression model is the way that we deal with continuous output in the way of predicting this output, but first, we need to train this model on some data, evaluate the model, get the best parameters that minimize the cost function.

The way we can train the model is differned:

- There is a closed-form using Normal Equation.
- And there is an iterative form using the Gradient Descent.

Linear_model(h_Θ or y_hat or Predicited value) = **  Θ_0 + Θ_1X **, so the model trying to predict the output by:

- Computing weighted sum for the input futures X multipled by some Θ(paramters or weights).
- Add constant term called bias  or intercept

**Θ** is the paprmaters that contain Θ_0 bias term + [Θ_1 - Θ_n] the weights assicated with the features [x_1 - x_n].


# Normal Equation

We can get the values of Θ that minimize the cost function very well directly in one step, but like this operation can work in case of up to (10000) number of features because of the complexity of multiplication then inversing about O(n3), one the other hand it can cause error when X is not invertible (singular), and in like this case we can use another function that get the ineverse anyway.

<img src="images/1.png" width="200" height="200">

- T means Transpose of the matrix.
- -1 means the inverse of the matrix.

# Graident Decsent

**A different way to train Linear Model is using Gradient Descent, in the case of a large number of features we have.**

**"Gradient Descent is a very generic optimization algorithm capable of finding optimal solutions to a widerange of problems. The general idea of Gradient Descent is to tweak parameters iteratively in order tominimize a cost function. " **

<table><tr>
<td> <img src="images/3.png" style="width: 400; height:300px"/> </td>
<td> <img src="images/4.png" style="width: 400;  height:300px"/> </td>
<td> <img src="images/5.png" style="width: 400;  height:300px"/> </td>
</tr></table>

As we are in Linear Regression we search for the parameters that minimize the cost function**MSE**, here is the linear regression using the Gradient Descent we should go through a number of iteration to optimize these thetas to minimize the cost function, the way we minimize wights are different in the step the model takes from one iteration to another which called **learning Rate**, as we can see in graph how different **Learning Rate**, lead to the result but one of the models take a too long time or steps to reach the global minimum and other one jump out the global(Model diverge).

The best one is this one that the model reaches the global minimum in such a good number of iterations.

# Note 

**The learning step size is proportional to the slope of the cost function, so the steps gradually get smaller as the parameters approach the minimum.**

As we can see we have some of the hyperparamters:

- The number of iteration the model need for converge
- The learning Reate value

Not all cost function looks nice (Regular Bowls) as we have in MSE, some of the cost function we need to minimize have holes, ridges, plateaus and all sorts of irregular shapes, and to make converge to the global minimum is difficult and as we can see in the graph may be in the local minimum instead of Global minimum, as well as take too much time to cross the plateau on the right of the graph.


<img src="images/6.png" style="width: 400; height:300px"/>

**"Fortunately, the MSE cost function for a Linear Regression model happens to be a convex function, whichmeans that if you pick any two points on the curve, the line segment joining them never crosses the curve.

- This implies that there are no local minima, just one global minimum.
- It is also a continuous function withn a slope that never changes abruptly.

These two facts have a great consequence: Gradient Descent isguaranteed to approach arbitrarily close the global minimum (if you wait long enough and if the learningrate is not too high)."**

The cost function has the shape of a bowl, but if the features have different ranges it can cause the shape to be an elongated bowl, so it will take a long time, because small ranges take a too long time to change.

<img src="images/7.png" style="width: 400; height:300px"/>

In [9]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [10]:
# Now lets do it on the whole dataset
predictions = lin_reg.predict(X_train)
error = mean_squared_error(predictions, y_train)
error

0.09232909368981741

In [11]:
# Now lets do it on the whole dataset
predictions = lin_reg.predict(X_test)
error = mean_squared_error(predictions, y_test)
error

0.08968361157441745